In [115]:
import numpy as np
import pandas as pd

In [116]:
a = [pd.Series([1.0,2.0,3.6],index=["a","b","c"],name="huha"),pd.Series([1.0,2.0,3.0,4.0],index=["a","b","c","d"],name="try")]
pd.DataFrame(a)

        a    b    c    d
huha  1.0  2.0  3.6  NaN
try   1.0  2.0  3.0  4.0

In [117]:
d = {
    "one": pd.Series([1.0,2.0,3.6],index=["a","b","c"]),
    "two": pd.Series([1.0,2.0,3.0,4.0],index=["a","b","c","d"])
}

df = pd.DataFrame(d)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.6  3.0
d  NaN  4.0

In [118]:
pd.DataFrame(d,index=["d","b","a"])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [119]:
pd.DataFrame(d,index=["d","b","a"],columns=["two","three"])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [120]:
print(df.index)

Index(['a', 'b', 'c', 'd'], dtype='object')

In [121]:
print(df.columns)

Index(['one', 'two'], dtype='object')

In [122]:
d1 = {
    "one": [1.0,2.0,3.0,4.0],
    "two": [4.0,3.0,2.0,1.0]
}

pd.DataFrame(d1,index=["a","b","c","d"])

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

DataFrames from structured or record arrays

In [123]:
data = np.zeros((2,),dtype=[("A","i4"),("B","f4"),])

In [124]:
data

array([(0, 0.), (0, 0.)], dtype=[('A', '<i4'), ('B', '<f4')])

In [125]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "S10")])
data

array([(0, 0., b''), (0, 0., b'')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [126]:
pd.DataFrame(data)

   A    B    C
0  0  0.0  b''
1  0  0.0  b''

In [127]:
data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]

In [128]:
pd.DataFrame(data)

   A    B         C
0  1  2.0  b'Hello'
1  2  3.0  b'World'

In [129]:
pd.DataFrame(data, index=["first", "second"])

        A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'

In [130]:
pd.DataFrame(data,columns=["C","B","A"])

          C    B  A
0  b'Hello'  2.0  1
1  b'World'  3.0  2

From a list of dicts

In [131]:
data2 = [{"a":1,"b":2},{"a":5,"b":10,"c":20}]
pd.DataFrame(data2)

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [134]:
df = pd.DataFrame(data2,index=["first","second"],columns=["a","b","c"])
df

        a   b     c
first   1   2   NaN
second  5  10  20.0

In [140]:
df.loc["first"]

a    1.0
b    2.0
c    NaN
Name: first, dtype: float64

From a dict of tuples

In [ ]:
pd.DataFrame(
    {
        ("a","b"):{("A","B"):1, ("A","C"):2},
        ("a","a"):{("A","C"):3, ("A","B"):4},
        ("a","c"):{("A","B"):5, ("A","C"):6},
        ("b","a"):{("A","C"):7, ("A","B"):8},
        ("b","b"):{("A","D"):9, ("A","B"):10}
    }
)

       a              b
       b    a    c    a     b
A B  1.0  4.0  5.0  8.0  10.0
  C  2.0  3.0  6.0  7.0   NaN
  D  NaN  NaN  NaN  NaN   9.0

From a series

In [ ]:
ser = pd.Series(range(3),index=list("abc"),name="ser")
pd.DataFrame(ser)

   ser
a    0
b    1
c    2