In [2]:
import numpy as np
import pandas as pd

In [3]:
d = {
    "one": pd.Series([1.0,2.0,3.6],index=["a","b","c"]),
    "two": pd.Series([1.0,2.0,3.0,4.0],index=["a","b","c","d"])
}

df = pd.DataFrame(d)
df

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.6  3.0
d  NaN  4.0

In [4]:
pd.DataFrame(d,index=["d","b","a"])

   one  two
d  NaN  4.0
b  2.0  2.0
a  1.0  1.0

In [5]:
pd.DataFrame(d,index=["d","b","a"],columns=["two","three"])

   two three
d  4.0   NaN
b  2.0   NaN
a  1.0   NaN

In [6]:
print(df.index)

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
print(df.columns)

Index(['one', 'two'], dtype='object')

In [8]:
d1 = {
    "one": [1.0,2.0,3.0,4.0],
    "two": [4.0,3.0,2.0,1.0]
}

pd.DataFrame(d1,index=["a","b","c","d"])

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

DataFrames from structured or record arrays

In [9]:
data = np.zeros((2,),dtype=[("A","i4"),("B","f4"),])